project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Week 3"
            href: "hands-on_ex/hands-on_ex02/hands-on_ex02.html"
          - text: "Week 4"
            href: "hands-on_ex/hands-on_ex03/hands-on_ex03.html"
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 02"
            href: "in-class_ex/in-class_ex02/in-class_ex02.html"
          - text: "In-Class Exercise 03"
            href: "in-class_ex/in-class_ex03/in-class_ex03.html"
          - text: "In-Class Exercise 04"
            href: "in-class_ex/in-class_ex04/in-class_ex04.html"
          - text: "In-Class Exercise 05"
            href: "in-class_ex/in-class_ex05/in-class_ex05.html"
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-Home Exercise 01"
            href: "take-home_ex/take-home_ex01/take-home_ex01.html"

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

