project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Week 3"
            href: "hands-on_ex/hands-on_ex02/hands-on_ex02.html"
          - text: "Week 4"
            href: "hands-on_ex/hands-on_ex03/hands-on_ex03.html"
          - text: "Week 7A"
            href: "hands-on_ex/hands-on_ex05/hands-on_ex05.html"
          - text: "Week 7B"
            href: "hands-on_ex/hands-on_ex06/hands-on_ex06.html"
          - text: "Week 9"
            href: "hands-on_ex/hands-on_ex07/hands-on_ex07.html"
          - text: "Week 10"
            href: "hands-on_ex/hands-on_ex08/hands-on_ex08.html"
          - text: "Week 11"
            href: "hands-on_ex/hands-on_ex09/hands-on_ex09.html"
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 02"
            href: "in-class_ex/in-class_ex02/in-class_ex02.html"
          - text: "In-Class Exercise 03"
            href: "in-class_ex/in-class_ex03/in-class_ex03.html"
          - text: "In-Class Exercise 04"
            href: "in-class_ex/in-class_ex04/in-class_ex04.html"
          - text: "In-Class Exercise 05"
            href: "in-class_ex/in-class_ex05/in-class_ex05.html"
          - text: "In-Class Exercise 06"
            href: "in-class_ex/in-class_ex06/in-class_ex06.html"
          - text: "In-Class Exercise 07"
            href: "in-class_ex/in-class_ex07/in-class_ex07.html"
          - text: "In-Class Exercise 08"
            href: "in-class_ex/in-class_ex08/in-class_ex08.html"
          - text: "In-Class Exercise 09"
            href: "in-class_ex/in-class_ex09/in-class_ex09.html"
          - text: "In-Class Exercise 10"
            href: "in-class_ex/in-class_ex10/in-class_ex10.html"
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-Home Exercise 01"
            href: "take-home_ex/take-home_ex01/take-home_ex01.html"
          - text: "Take-Home Exercise 02"
            href: "take-home_ex/take-home_ex02/take-home_ex02.html"
          - text: "Take-Home Exercise 03"
            href: "take-home_ex/take-home_ex02/take-home_ex03.html"

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

