project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "1 Geospatial Data Wrangling with R"
            href: "hands-on_ex/hands-on_ex02/hands-on_ex02.html"
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 02"
            href: "in-class_ex/in-class_ex02/in-class_ex02.html"

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

