<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-02-17">

<title>IS415-GAA - Take Home Exercise 02: Spatio-temporal Analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jakarta</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../hands-on_ex/hands-on_ex02/hands-on_ex02.html">
 <span class="dropdown-text">Week 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on_ex/hands-on_ex03/hands-on_ex03.html">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on_ex/hands-on_ex05/hands-on_ex05.html">
 <span class="dropdown-text">Week 7A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hands-on_ex/hands-on_ex06/hands-on_ex06.html">
 <span class="dropdown-text">Week 7B</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex02/in-class_ex02.html">
 <span class="dropdown-text">In-Class Exercise 02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex03/in-class_ex03.html">
 <span class="dropdown-text">In-Class Exercise 03</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex04/in-class_ex04.html">
 <span class="dropdown-text">In-Class Exercise 04</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex05/in-class_ex05.html">
 <span class="dropdown-text">In-Class Exercise 05</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex06/in-class_ex06.html">
 <span class="dropdown-text">In-Class Exercise 06</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../in-class_ex/in-class_ex07/in-class_ex07.html">
 <span class="dropdown-text">In-Class Exercise 07</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../take-home_ex/take-home_ex01/take-home_ex01.html">
 <span class="dropdown-text">Take-Home Exercise 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../take-home_ex/take-home_ex02/take-home_ex02.html">
 <span class="dropdown-text">Take-Home Exercise 02</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-context" id="toc-problem-context" class="nav-link active" data-scroll-target="#problem-context"><span class="toc-section-number">1</span>  Problem Context</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><span class="toc-section-number">2</span>  Objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="toc-section-number">3</span>  Setup</a>
  <ul class="collapse">
  <li><a href="#packages-used" id="toc-packages-used" class="nav-link" data-scroll-target="#packages-used"><span class="toc-section-number">3.1</span>  Packages used</a></li>
  <li><a href="#datasets-used" id="toc-datasets-used" class="nav-link" data-scroll-target="#datasets-used"><span class="toc-section-number">3.2</span>  Datasets used</a></li>
  </ul></li>
  <li><a href="#data-wrangling-geospatial-data" id="toc-data-wrangling-geospatial-data" class="nav-link" data-scroll-target="#data-wrangling-geospatial-data"><span class="toc-section-number">4</span>  Data Wrangling: Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data"><span class="toc-section-number">4.1</span>  Importing Geospatial Data</a></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing"><span class="toc-section-number">4.2</span>  Data pre-processing</a></li>
  </ul></li>
  <li><a href="#data-wrangling-aspatial-data" id="toc-data-wrangling-aspatial-data" class="nav-link" data-scroll-target="#data-wrangling-aspatial-data"><span class="toc-section-number">5</span>  Data Wrangling: Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data"><span class="toc-section-number">5.1</span>  Importing Aspatial Data</a></li>
  </ul></li>
  <li><a href="#task-1-choropleth-mapping-and-analysis" id="toc-task-1-choropleth-mapping-and-analysis" class="nav-link" data-scroll-target="#task-1-choropleth-mapping-and-analysis"><span class="toc-section-number">6</span>  Task 1: Choropleth Mapping and Analysis</a>
  <ul class="collapse">
  <li><a href="#combining-both-data-frames-using-left_join" id="toc-combining-both-data-frames-using-left_join" class="nav-link" data-scroll-target="#combining-both-data-frames-using-left_join"><span class="toc-section-number">6.1</span>  Combining both data frames using <code>left_join()</code></a></li>
  <li><a href="#mapping-the-distribution-of-vaccination-rate-for-dki-jakarta-over-12-months" id="toc-mapping-the-distribution-of-vaccination-rate-for-dki-jakarta-over-12-months" class="nav-link" data-scroll-target="#mapping-the-distribution-of-vaccination-rate-for-dki-jakarta-over-12-months"><span class="toc-section-number">6.2</span>  Mapping the Distribution of Vaccination Rate for DKI Jakarta over 12 months</a></li>
  <li><a href="#observations-from-equal-interval-choropleth-maps-with-custom-breakpoints" id="toc-observations-from-equal-interval-choropleth-maps-with-custom-breakpoints" class="nav-link" data-scroll-target="#observations-from-equal-interval-choropleth-maps-with-custom-breakpoints"><span class="toc-section-number">6.3</span>  Observations from Equal Interval Choropleth Maps with Custom Breakpoints</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 02: Spatio-temporal Analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jakarta</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 17, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 28, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="problem-context" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="problem-context"><span class="header-section-number">1</span> Problem Context</h2>
<p>In late December 2019, the COVID-19 outbreak was reported in Wuhan, China, which had subsequently affected 210 countries worldwide. COVID-19 can be deadly with a 2% case fatality rate.</p>
<p>In response to this, Indonesia commenced its COVID-19 vaccination program on 13 January 2021, and as of 5 February 2023, over 204 million people had received the first dose of the vaccine, and over 175 million people had been fully vaccinated, with Jakarta having the highest percentage of population fully vaccinated.</p>
<p>However despite its compactness, the cumulative vaccination rate are not evenly distributed within DKI Jakarta. The question is where are the sub-districts with a relatively higher number of vaccination rate and how have they changed over time.</p>
<p>The assignment can be found <a href="https://is415-ay2022-23t2.netlify.app/th_ex2.html">here</a>.</p>
</section>
<section id="objectives" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="objectives"><span class="header-section-number">2</span> Objectives</h2>
<p>Exploratory Spatial Data Analysis (ESDA) holds tremendous potential to address complex problems facing society. In this study, we will need to use it to uncover the spatio-temporal trends of COVID-19 vaccination in DKI Jakarta namely:</p>
<ul>
<li><p>Choropleth Mapping and Analysis</p></li>
<li><p>Local Gi* Analysis</p></li>
<li><p>Emerging Hot Spot Analysis (EHSA)</p></li>
</ul>
</section>
<section id="setup" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="setup"><span class="header-section-number">3</span> Setup</h2>
<section id="packages-used" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="packages-used"><span class="header-section-number">3.1</span> Packages used</h3>
<p>These are the R packages that we’ll need for our analyses:</p>
<ul>
<li><p><strong>sf</strong> - used for importing, managing, and processing geospatial data</p></li>
<li><p><strong>sfdep</strong> - an <code>sf</code> and <code>tidyverse</code> friendly interface to compute spatial dependence</p></li>
<li><p><strong>tidyverse</strong> - collection of packages for performing data science tasks such as importing, wrangling, and visualising data</p></li>
<li><p><strong>tmap</strong> - for plotting cartographic quality static point patterns maps or interactive maps by using <a href="https://leafletjs.com/">leaflet</a> API</p></li>
<li><p><strong>readxl</strong> - for reading .xlsx files. It is part of the <code>tidyverse</code> collection.</p></li>
<li><p><strong>hash</strong> - used to create a hash object. I have used this to convert the month spelling from Bahasa Indonesia to English. This is done so that when the data is visualised it is clear to all.</p></li>
<li><p><strong>moments</strong> - used to call the <code>skewness()</code> function to calculate skewness of the data.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, sfdep, tidyverse, tmap, hash, moments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="datasets-used" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="datasets-used"><span class="header-section-number">3.2</span> Datasets used</h3>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Name</th>
<th>Format</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geospatial</td>
<td><a href="https://www.indonesia-geospasial.com/2020/04/download-shapefile-shp-batas-desa.html">DKI Jakarta Provincial Village Boundary</a></td>
<td>.shp</td>
<td>District level boundary in DKI Jakarta. Please take note that the data is from 2019.</td>
</tr>
<tr class="even">
<td>Aspatial</td>
<td><a href="https://riwayat-file-vaksinasi-dki-jakarta-jakartagis.hub.arcgis.com/">District Based Vaccination History</a></td>
<td>.xlsx</td>
<td><p>Daily .csv files containing all vaccinations done at the sub-district level (i.e., kelurahan) in DKI Jakarta. The files consider the number of doses given to the following groups of people:</p>
<ul>
<li><p>Mutual Cooperation Vaccination (Ages 18+)</p></li>
<li><p>Vaccination of Health Workers (Ages 18+)</p></li>
<li><p>Elderly Vaccination (Ages 18+)</p></li>
<li><p>Public Service Vaccination (Ages 18+)</p></li>
<li><p>Stage 3 Vaccination (General Community, Pre-Elderly, Vulnerable)</p></li>
<li><p>Youth Vaccination (Ages 12-17)</p></li>
</ul></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-wrangling-geospatial-data" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="data-wrangling-geospatial-data"><span class="header-section-number">4</span> Data Wrangling: Geospatial Data</h2>
<section id="importing-geospatial-data" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="importing-geospatial-data"><span class="header-section-number">4.1</span> Importing Geospatial Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"data/geospatial"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">layer=</span><span class="st">"BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA' from data source 
  `C:\guga-nesh\IS415-GAA\take-home_ex\take-home_ex02\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 269 features and 161 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 106.3831 ymin: -6.370815 xmax: 106.9728 ymax: -5.184322
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>Information gathered on <code>jakarta</code> :</p>
<ul>
<li><p>Data Type: <strong>sf</strong> collection</p></li>
<li><p>Geometry Type: Multipolygon</p></li>
<li><p>Shape: 269 features, 161 fields</p></li>
<li><p>CRS: WGS 84 - ‘The World Geodetic System (WGS)’.</p></li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The assigned CRS does not seem appropriate. In fact, the assignment requires us to re-assign the CRS to DGN95. We’ll fix this in Section 4.2.3.</p>
</div>
</div>
</section>
<section id="data-pre-processing" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="data-pre-processing"><span class="header-section-number">4.2</span> Data pre-processing</h3>
<p>Before we can visualise our data, we need to ensure that the data is validated by handling invalid geometries and missing values.</p>
<p><em>This section was done by referencing sample submissions done by two seniors, credit to:</em></p>
<ul>
<li><p><a href="https://rpubs.com/xiaorongw/IS415_Take-home_Ex02"><em>Xiao Rong Wong’s ‘Detecting Spatio-Temporal Patterns of COVID-19 in Central Mexico’</em></a></p></li>
<li><p><a href="https://is415-msty.netlify.app/posts/2021-09-10-take-home-exercise-1/#data-pre-processing"><em>Megan Sim Tze Yen’s ‘Analysing and Visualising Spatio-temporal Patterns of COVID-19 in DKI Jakarta, Indonesia’</em></a></p></li>
</ul>
<p>Afterwards, we can work on doing the pre-processing on the <code>jakarta</code> data as per the requirements of the assignment.</p>
<section id="handling-invalid-geometries" class="level4" data-number="4.2.1">
<h4 data-number="4.2.1" class="anchored" data-anchor-id="handling-invalid-geometries"><span class="header-section-number">4.2.1</span> Handling invalid geometries</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(jakarta) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>st_is_valid()</code> checks whether a geometry is valid. It returns a logical vector indicating for each geometries of <code>jakarta</code> whether it is valid. The documentation for this can be found <a href="https://r-spatial.github.io/sf/reference/valid.html">here</a>.</p>
</div>
</div>
<p>From the above output, we can see that the geometry is valid 👍</p>
</section>
<section id="handling-missing-values" class="level4" data-number="4.2.2">
<h4 data-number="4.2.2" class="anchored" data-anchor-id="handling-missing-values"><span class="header-section-number">4.2.2</span> Handling missing values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>jakarta[<span class="fu">rowSums</span>(<span class="fu">is.na</span>(jakarta))<span class="sc">!=</span><span class="dv">0</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 161 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 106.8412 ymin: -6.154036 xmax: 106.8612 ymax: -6.144973
Geodetic CRS:  WGS 84
    OBJECT_ID KODE_DESA             DESA   KODE    PROVINSI KAB_KOTA KECAMATAN
243     25645  31888888     DANAU SUNTER 318888 DKI JAKARTA     &lt;NA&gt;      &lt;NA&gt;
244     25646  31888888 DANAU SUNTER DLL 318888 DKI JAKARTA     &lt;NA&gt;      &lt;NA&gt;
    DESA_KELUR JUMLAH_PEN JUMLAH_KK LUAS_WILAY KEPADATAN PERPINDAHA JUMLAH_MEN
243       &lt;NA&gt;          0         0          0         0          0          0
244       &lt;NA&gt;          0         0          0         0          0          0
    PERUBAHAN WAJIB_KTP SILAM KRISTEN KHATOLIK HINDU BUDHA KONGHUCU KEPERCAYAA
243         0         0     0       0        0     0     0        0          0
244         0         0     0       0        0     0     0        0          0
    PRIA WANITA BELUM_KAWI KAWIN CERAI_HIDU CERAI_MATI U0 U5 U10 U15 U20 U25
243    0      0          0     0          0          0  0  0   0   0   0   0
244    0      0          0     0          0          0  0  0   0   0   0   0
    U30 U35 U40 U45 U50 U55 U60 U65 U70 U75 TIDAK_BELU BELUM_TAMA TAMAT_SD SLTP
243   0   0   0   0   0   0   0   0   0   0          0          0        0    0
244   0   0   0   0   0   0   0   0   0   0          0          0        0    0
    SLTA DIPLOMA_I DIPLOMA_II DIPLOMA_IV STRATA_II STRATA_III BELUM_TIDA
243    0         0          0          0         0          0          0
244    0         0          0          0         0          0          0
    APARATUR_P TENAGA_PEN WIRASWASTA PERTANIAN NELAYAN AGAMA_DAN PELAJAR_MA
243          0          0          0         0       0         0          0
244          0          0          0         0       0         0          0
    TENAGA_KES PENSIUNAN LAINNYA GENERATED KODE_DES_1 BELUM_ MENGUR_ PELAJAR_
243          0         0       0      &lt;NA&gt;       &lt;NA&gt;      0       0        0
244          0         0       0      &lt;NA&gt;       &lt;NA&gt;      0       0        0
    PENSIUNA_1 PEGAWAI_ TENTARA KEPOLISIAN PERDAG_ PETANI PETERN_ NELAYAN_1
243          0        0       0          0       0      0       0         0
244          0        0       0          0       0      0       0         0
    INDUSTR_ KONSTR_ TRANSP_ KARYAW_ KARYAW1 KARYAW1_1 KARYAW1_12 BURUH BURUH_
243        0       0       0       0       0         0          0     0      0
244        0       0       0       0       0         0          0     0      0
    BURUH1 BURUH1_1 PEMBANT_ TUKANG TUKANG_1 TUKANG_12 TUKANG__13 TUKANG__14
243      0        0        0      0        0         0          0          0
244      0        0        0      0        0         0          0          0
    TUKANG__15 TUKANG__16 TUKANG__17 PENATA PENATA_ PENATA1_1 MEKANIK SENIMAN_
243          0          0          0      0       0         0       0        0
244          0          0          0      0       0         0       0        0
    TABIB PARAJI_ PERANCA_ PENTER_ IMAM_M PENDETA PASTOR WARTAWAN USTADZ JURU_M
243     0       0        0       0      0       0      0        0      0      0
244     0       0        0       0      0       0      0        0      0      0
    PROMOT ANGGOTA_ ANGGOTA1 ANGGOTA1_1 PRESIDEN WAKIL_PRES ANGGOTA1_2
243      0        0        0          0        0          0          0
244      0        0        0          0        0          0          0
    ANGGOTA1_3 DUTA_B GUBERNUR WAKIL_GUBE BUPATI WAKIL_BUPA WALIKOTA WAKIL_WALI
243          0      0        0          0      0          0        0          0
244          0      0        0          0      0          0        0          0
    ANGGOTA1_4 ANGGOTA1_5 DOSEN GURU PILOT PENGACARA_ NOTARIS ARSITEK AKUNTA_
243          0          0     0    0     0          0       0       0       0
244          0          0     0    0     0          0       0       0       0
    KONSUL_ DOKTER BIDAN PERAWAT APOTEK_ PSIKIATER PENYIA_ PENYIA1 PELAUT
243       0      0     0       0       0         0       0       0      0
244       0      0     0       0       0         0       0       0      0
    PENELITI SOPIR PIALAN PARANORMAL PEDAGA_ PERANG_ KEPALA_ BIARAW_ WIRASWAST_
243        0     0      0          0       0       0       0       0          0
244        0     0      0          0       0       0       0       0          0
    LAINNYA_12 LUAS_DESA KODE_DES_3 DESA_KEL_1 KODE_12
243          0         0       &lt;NA&gt;       &lt;NA&gt;       0
244          0         0       &lt;NA&gt;       &lt;NA&gt;       0
                          geometry
243 MULTIPOLYGON (((106.8612 -6...
244 MULTIPOLYGON (((106.8504 -6...</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>rowSums()</code> method calculates the sum of each row of a data frame. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/raster/versions/3.6-14/topics/rowSums">here</a>.</p>
<p><code>is.na()</code> is a generic method that indicates which elements are missing. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/NA">here</a>.</p>
<p><code>jakarta</code> ‘wrapper’ prints rows that contain NA values.</p>
</div>
</div>
<p>From the output shown above we can see that there are NA values 👎</p>
<p>In fact, there are two rows with missing values. However, it’s hard to tell which columns the NA values are in since the output is so long and messy. Let’s just retrieve the columns with missing values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(jakarta))<span class="sc">&gt;</span><span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "KAB_KOTA"   "KECAMATAN"  "DESA_KELUR" "GENERATED"  "KODE_DES_1"
[6] "KODE_DES_3" "DESA_KEL_1"</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>colSum()</code> helps form sum for data frame by column. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/Matrix/versions/1.5-3/topics/colSums">here</a>.</p>
<p><code>which()</code> gives the TRUE indices of a logical object, allowing for array indices. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/which">here</a>.</p>
<p><code>names()</code> is used to get or set the names of an object. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/names">here</a>.</p>
</div>
</div>
<p>There are two rows with missing values in the columns shown above. Let’s see what they mean… Google Translate tells us that: 🤔</p>
<ul>
<li><p>“KAB_KOTA” = REGENCY_CITY</p></li>
<li><p>“KECAMATAN” = SUB-DISTRICT</p></li>
<li><p>“DESA_KELUR” = VILLAGE_KELUR</p></li>
</ul>
<p>We can remove all rows with missing values under the “DESA_KELUR” (i.e., VILLAGE level) column since we are only interested in the sub-district and potentially city level data.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Later we find out that the definition of these columns by Google Translate are not 100% accurate. But it’s okay as this does not affect our analysis for now.</p>
</div>
</div>
<p><em>Nonetheless, it should be noted that in this particular case removing the missing values from any of the columns will yield the same result.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(jakarta, <span class="fu">c</span>(<span class="st">"DESA_KELUR"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>na.omit()</code> is used to handle missing values in objects. In this case, we input the <code>object</code>(must be an R object) and the <code>target.colnames</code> (a vector of names for the target columns to operate upon, if present in <code>object</code>. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/photobiology/versions/0.10.6/topics/na.omit">here</a>.</p>
</div>
</div>
<p>Let’s check if we have removed the rows with missing values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>jakarta[<span class="fu">rowSums</span>(<span class="fu">is.na</span>(jakarta))<span class="sc">!=</span><span class="dv">0</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 0 features and 161 fields
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
Geodetic CRS:  WGS 84
  [1] OBJECT_ID  KODE_DESA  DESA       KODE       PROVINSI   KAB_KOTA  
  [7] KECAMATAN  DESA_KELUR JUMLAH_PEN JUMLAH_KK  LUAS_WILAY KEPADATAN 
 [13] PERPINDAHA JUMLAH_MEN PERUBAHAN  WAJIB_KTP  SILAM      KRISTEN   
 [19] KHATOLIK   HINDU      BUDHA      KONGHUCU   KEPERCAYAA PRIA      
 [25] WANITA     BELUM_KAWI KAWIN      CERAI_HIDU CERAI_MATI U0        
 [31] U5         U10        U15        U20        U25        U30       
 [37] U35        U40        U45        U50        U55        U60       
 [43] U65        U70        U75        TIDAK_BELU BELUM_TAMA TAMAT_SD  
 [49] SLTP       SLTA       DIPLOMA_I  DIPLOMA_II DIPLOMA_IV STRATA_II 
 [55] STRATA_III BELUM_TIDA APARATUR_P TENAGA_PEN WIRASWASTA PERTANIAN 
 [61] NELAYAN    AGAMA_DAN  PELAJAR_MA TENAGA_KES PENSIUNAN  LAINNYA   
 [67] GENERATED  KODE_DES_1 BELUM_     MENGUR_    PELAJAR_   PENSIUNA_1
 [73] PEGAWAI_   TENTARA    KEPOLISIAN PERDAG_    PETANI     PETERN_   
 [79] NELAYAN_1  INDUSTR_   KONSTR_    TRANSP_    KARYAW_    KARYAW1   
 [85] KARYAW1_1  KARYAW1_12 BURUH      BURUH_     BURUH1     BURUH1_1  
 [91] PEMBANT_   TUKANG     TUKANG_1   TUKANG_12  TUKANG__13 TUKANG__14
 [97] TUKANG__15 TUKANG__16 TUKANG__17 PENATA     PENATA_    PENATA1_1 
[103] MEKANIK    SENIMAN_   TABIB      PARAJI_    PERANCA_   PENTER_   
[109] IMAM_M     PENDETA    PASTOR     WARTAWAN   USTADZ     JURU_M    
[115] PROMOT     ANGGOTA_   ANGGOTA1   ANGGOTA1_1 PRESIDEN   WAKIL_PRES
[121] ANGGOTA1_2 ANGGOTA1_3 DUTA_B     GUBERNUR   WAKIL_GUBE BUPATI    
[127] WAKIL_BUPA WALIKOTA   WAKIL_WALI ANGGOTA1_4 ANGGOTA1_5 DOSEN     
[133] GURU       PILOT      PENGACARA_ NOTARIS    ARSITEK    AKUNTA_   
[139] KONSUL_    DOKTER     BIDAN      PERAWAT    APOTEK_    PSIKIATER 
[145] PENYIA_    PENYIA1    PELAUT     PENELITI   SOPIR      PIALAN    
[151] PARANORMAL PEDAGA_    PERANG_    KEPALA_    BIARAW_    WIRASWAST_
[157] LAINNYA_12 LUAS_DESA  KODE_DES_3 DESA_KEL_1 KODE_12    geometry  
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>Looks good! 😎 But we still have 3 other pre-processing steps to do…</p>
</section>
<section id="re-assign-coordinate-reference-system-crs" class="level4" data-number="4.2.3">
<h4 data-number="4.2.3" class="anchored" data-anchor-id="re-assign-coordinate-reference-system-crs"><span class="header-section-number">4.2.3</span> Re-assign Coordinate Reference System (CRS)</h4>
<p>The CRS of <code>jakarta</code> is WGS 84. The assignment requires us to use the national CRS of Indonesia <a href="https://epsg.io/23845"><em>( DGN95 / Indonesia TM-3 zone 54.1)</em></a> since our dataset is specific to Indonesia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>Let’s re-assign using EPSG code 23845 and check the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(jakarta, <span class="dv">23845</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:23845 
  wkt:
PROJCRS["DGN95 / Indonesia TM-3 zone 54.1",
    BASEGEOGCRS["DGN95",
        DATUM["Datum Geodesi Nasional 1995",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4755]],
    CONVERSION["Indonesia TM-3 zone 54.1",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",139.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9999,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",1500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre."],
        AREA["Indonesia - onshore east of 138°E."],
        BBOX[-9.19,138,-1.49,141.01]],
    ID["EPSG",23845]]</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>st_transform()</code> is used to transform or convert coordinates of a simple feature. Please refer to the documentation <a href="https://search.r-project.org/CRAN/refmans/sf/html/st_transform.html">here</a>.</p>
<p><code>st_crs()</code> is used to retrieve the coordinate reference system from an <strong>sf</strong> or <strong>sfc</strong> object. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/sf/versions/0.2-4/topics/st_crs">here</a>.</p>
</div>
</div>
</section>
<section id="exclude-all-outer-islands-from-jakarta" class="level4" data-number="4.2.4">
<h4 data-number="4.2.4" class="anchored" data-anchor-id="exclude-all-outer-islands-from-jakarta"><span class="header-section-number">4.2.4</span> Exclude all outer islands from <code>jakarta</code></h4>
<p>The assignment requires us to remove all outer islands from <code>jakarta</code>. Let’s plot the geometry of <code>jakarta</code> to see what we’re working with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(jakarta[<span class="st">'geometry'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the visualisation above, we can see that there are some outer islands scattered towards the north. Let’s remove them.</p>
<p>In Section 4.2.2, we saw that the data is grouped by <strong><em>KAB_KOTA</em></strong> (i.e., CITY), <strong><em>KECAMATAN</em></strong> (i.e., SUB-DISTRICT), and <strong><em>DESA_KELUR</em></strong> (i.e., “VILLAGE”). Let’s see the different cities we have in DKI Jakarta.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(jakarta<span class="sc">$</span>KAB_KOTA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "JAKARTA BARAT"    "JAKARTA PUSAT"    "KEPULAUAN SERIBU" "JAKARTA UTARA"   
[5] "JAKARTA TIMUR"    "JAKARTA SELATAN" </code></pre>
</div>
</div>
<p>The output shows us that there are 6 different cities in DKI Jakarta. 5 of them are prefixed with the string “JAKARTA” while one of them isn’t. Let’s plot this data to see if the one without the prefix represents the outer islands.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(jakarta) <span class="sc">+</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"KAB_KOTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems our suspicions are correct, the outer islands are those cities without the “JAKARTA” prefix. In fact, according to Google Translate, “KEPULAUAN SEBIRU” can be directly translated to “Thousand Islands” in English. Let’s remove them and check the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> jakarta <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"JAKARTA"</span>, KAB_KOTA))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(jakarta<span class="sc">$</span>KAB_KOTA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "JAKARTA BARAT"   "JAKARTA PUSAT"   "JAKARTA UTARA"   "JAKARTA TIMUR"  
[5] "JAKARTA SELATAN"</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>grepl()</code> is used to search for matches to argument <code>pattern</code> (in our case its “JAKARTA”) within each element of a character vector. Please find the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/grep">here</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(jakarta<span class="sc">$</span>geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looks good! 😎</p>
</section>
<section id="retain-first-nine-fields-in-jakarta" class="level4" data-number="4.2.5">
<h4 data-number="4.2.5" class="anchored" data-anchor-id="retain-first-nine-fields-in-jakarta"><span class="header-section-number">4.2.5</span> Retain first nine fields in <code>jakarta</code></h4>
<p>The assignment requires us to only retain the first 9 fields of the <strong>sf</strong> data frame. Let’s do this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> jakarta[,<span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>jakarta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 261 features and 9 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -3644275 ymin: 663887.8 xmax: -3606237 ymax: 701380.1
Projected CRS: DGN95 / Indonesia TM-3 zone 54.1
First 10 features:
   OBJECT_ID  KODE_DESA               DESA   KODE    PROVINSI      KAB_KOTA
1      25477 3173031006          KEAGUNGAN 317303 DKI JAKARTA JAKARTA BARAT
2      25478 3173031007             GLODOK 317303 DKI JAKARTA JAKARTA BARAT
3      25397 3171031003      HARAPAN MULIA 317103 DKI JAKARTA JAKARTA PUSAT
4      25400 3171031006       CEMPAKA BARU 317103 DKI JAKARTA JAKARTA PUSAT
5      25390 3171021001         PASAR BARU 317102 DKI JAKARTA JAKARTA PUSAT
6      25391 3171021002       KARANG ANYAR 317102 DKI JAKARTA JAKARTA PUSAT
7      25394 3171021005 MANGGA DUA SELATAN 317102 DKI JAKARTA JAKARTA PUSAT
8      25386 3171011003       PETOJO UTARA 317101 DKI JAKARTA JAKARTA PUSAT
9      25403 3171041001              SENEN 317104 DKI JAKARTA JAKARTA PUSAT
10     25408 3171041006             BUNGUR 317104 DKI JAKARTA JAKARTA PUSAT
     KECAMATAN         DESA_KELUR JUMLAH_PEN                       geometry
1   TAMAN SARI          KEAGUNGAN      21609 MULTIPOLYGON (((-3626874 69...
2   TAMAN SARI             GLODOK       9069 MULTIPOLYGON (((-3627130 69...
3    KEMAYORAN      HARAPAN MULIA      29085 MULTIPOLYGON (((-3621251 68...
4    KEMAYORAN       CEMPAKA BARU      41913 MULTIPOLYGON (((-3620608 69...
5  SAWAH BESAR         PASAR BARU      15793 MULTIPOLYGON (((-3624097 69...
6  SAWAH BESAR       KARANG ANYAR      33383 MULTIPOLYGON (((-3624785 69...
7  SAWAH BESAR MANGGA DUA SELATAN      35906 MULTIPOLYGON (((-3624752 69...
8       GAMBIR       PETOJO UTARA      21828 MULTIPOLYGON (((-3626121 69...
9        SENEN              SENEN       8643 MULTIPOLYGON (((-3623189 69...
10       SENEN             BUNGUR      23001 MULTIPOLYGON (((-3622451 69...</code></pre>
</div>
</div>
<p>From the assignment we know that the ninth field is “JUMLAH_PEN”. The output generated above matches this information.</p>
</section>
<section id="rename-columns-for-better-understanding" class="level4" data-number="4.2.6">
<h4 data-number="4.2.6" class="anchored" data-anchor-id="rename-columns-for-better-understanding"><span class="header-section-number">4.2.6</span> Rename Columns for better understanding</h4>
<p>For better understanding of the data, let us rename the columns to their English translation. For this we will use the <code>rename()</code> function.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since Google Translate has been giving me contradicting answers 😓, I have decided to use this <a href="https://en.wikipedia.org/wiki/Subdivisions_of_Indonesia">wiki page</a> as a guide.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take note of the hierarchy of subdivisions of Indonesia</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>jakarta <span class="ot">&lt;-</span> jakarta <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">object_id =</span> OBJECT_ID,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">village_code =</span> KODE_DESA,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fifth level</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">village =</span> DESA,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">code =</span> KODE,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># first level</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">province =</span> PROVINSI,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># second level</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">city =</span> KAB_KOTA,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># third level</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">district =</span> KECAMATAN,</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fourth level - assumption made: KELUR = KELURAHAN</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">sub_district =</span> DESA_KELUR,</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_population =</span> JUMLAH_PEN</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>rename()</code> is a method under the <strong>dplyr</strong> library. It changes the names of individual variables using the <code>new_name = old_name</code> syntax.</p>
<p>side note: <code>rename_with()</code> renames columns using a function. Please refer to the documentation <a href="https://dplyr.tidyverse.org/reference/rename.html">here</a>.</p>
</div>
</div>
<p>We have completed the data pre-processing steps for the geospatial data 🥳 Let’s move on to the aspatial data.</p>
</section>
</section>
</section>
<section id="data-wrangling-aspatial-data" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="data-wrangling-aspatial-data"><span class="header-section-number">5</span> Data Wrangling: Aspatial Data</h2>
<p>In this section, we’ll be importing and performing some basic pre-processing on the COVID-19 vaccination datasets.</p>
<section id="importing-aspatial-data" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="importing-aspatial-data"><span class="header-section-number">5.1</span> Importing Aspatial Data</h3>
<p>The assignment requires us to compute the vaccination rate from July 2021 to June 2022 at the sub-district (i.e., kelurahan) level.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will be taking the data compiled on the <u><strong>last day</strong></u> of each month to retrieve the monthly records of COVID-19 vaccinations from the above-mentioned time period.</p>
</div>
</div>
<section id="primary-data-exploration" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="primary-data-exploration"><span class="header-section-number">5.1.1</span> Primary Data Exploration</h4>
<p>Since we will need to import 12 files (which is a lot), let’s look at the structure of one of them to figure what kind of data we have and how we can pre-process it moving forward.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>july_2021 <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Juli 2021).xlsx"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(july_2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 4441501, 12333, 13875, 18…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 4499710, 11614, 15506, 10…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 1663218, 4181, 4798, 3658…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 6162928, 15795, 20304, 14…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 502579, 1230, 2012, 865, …
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 440910, 1069, 1729, 701, …
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 943489, 2299, 3741, 1566,…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1052883, 3333, 2586, 2837…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 666009, 2158, 1374, 1761,…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 1718892, 5491, 3960, 4598…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 56660, 78, 122, 174, 71, …
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 38496, 51, 84, 106, 57, 7…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 95156, 129, 206, 280, 128…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 76397, 101, 90, 215, 73, …
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 67484, 91, 82, 192, 67, 3…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 143881, 192, 172, 407, 14…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 2279398, 5506, 9012, 5408…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 446028, 789, 1519, 897, 4…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 2725426, 6295, 10531, 630…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 531793, 1366, 1684, 1261,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 4291, 23, 10, 1, 1, 8, 6,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 536084, 1389, 1694, 1262,…</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>read_xlsx()</code> reads data from a .xlsx file. This function is from the <strong>readxl</strong> library under the <strong>tidyverse</strong> collection.</p>
<p><code>glimpse()</code> makes it easier to see every column in a data frame. Please refer to the documentation <a href="https://dplyr.tidyverse.org/reference/glimpse.html">here</a>.</p>
</div>
</div>
<p>Information gathered on <code>july_2021</code>:</p>
<ul>
<li><p>Data Type: <strong>tibble</strong> data frame</p></li>
<li><p>Shape: 268 entries, 27 columns</p></li>
</ul>
<p>There seems to be a quite a few columns…🤔</p>
<p>We will only need to take the “KELURAHAN” (i.e., sub- district level) , “SASARAN” (i.e., target) and the “BELUM VAKSIN” (i.e., number of people who have not been vaccinated yet) columns to calculate the vaccination rate for each month. We will look at how we can calculate this in Section 5.1.2.</p>
<p><em>I learnt that only these columns were necessary for our analysis after receiving some advice from Professor Kam Tin Seong. Thank you so much for your guidance prof!</em> 😃</p>
</section>
<section id="creating-a-function-to-process-our-aspatial-data" class="level4" data-number="5.1.2">
<h4 data-number="5.1.2" class="anchored" data-anchor-id="creating-a-function-to-process-our-aspatial-data"><span class="header-section-number">5.1.2</span> Creating a function to process our Aspatial Data</h4>
<p>First, let us get all the file names for our aspatial data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"data/aspatial"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>file.list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">pattern =</span> <span class="st">"*.xlsx"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>file.list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Data Vaksinasi Berbasis Kelurahan (27 Februari 2022).xlsx" 
 [2] "Data Vaksinasi Berbasis Kelurahan (30 April 2022).xlsx"    
 [3] "Data Vaksinasi Berbasis Kelurahan (30 Juni 2022).xlsx"     
 [4] "Data Vaksinasi Berbasis Kelurahan (30 November 2021).xlsx" 
 [5] "Data Vaksinasi Berbasis Kelurahan (30 September 2021).xlsx"
 [6] "Data Vaksinasi Berbasis Kelurahan (31 Agustus 2021).xlsx"  
 [7] "Data Vaksinasi Berbasis Kelurahan (31 Desember 2021).xlsx" 
 [8] "Data Vaksinasi Berbasis Kelurahan (31 Januari 2022).xlsx"  
 [9] "Data Vaksinasi Berbasis Kelurahan (31 Juli 2021).xlsx"     
[10] "Data Vaksinasi Berbasis Kelurahan (31 Maret 2022).xlsx"    
[11] "Data Vaksinasi Berbasis Kelurahan (31 Mei 2022).xlsx"      
[12] "Data Vaksinasi Berbasis Kelurahan (31 Oktober 2021).xlsx"  </code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>The above code chunk was referenced from <a href="https://stackoverflow.com/questions/32888757/how-can-i-read-multiple-excel-files-into-r">stackoverflow</a>. Credit to <a href="https://stackoverflow.com/users/2204410/jaap">Jaap</a> for his detailed answer there.</em></p>
<p><code>setwd("dir")</code> is used to set the working directory to string “dir”. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/getwd">here</a>.</p>
<p><code>library()</code> loads and attaches add-on packages. In this case, we need to use to <code>read_excel()</code> from <strong>readxl</strong>. Hence, we have loaded in that package. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/library">here</a>.</p>
<p><code>list.files()</code> is used to generate a vector of file names in the specified directory (from <code>setwd()</code>) with the pattern (“*.xlsx”). Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/list.files">here</a>.</p>
</div>
</div>
<p>Now, we are ready to create a function that processes all the files and merges all the data into a single sf data frame. Our output after all the pre-processing should look something like this:</p>
<p><img src="images/image-196486236.png" class="img-fluid"></p>
<p>We will be using two functions to achieve the above-shown skeleton of the data frame:</p>
<ul>
<li><p><code>get_month_year()</code> - this is used to get the English month and year of each file. The output will be put into the final data frame under the “MONTH.YEAR” column</p></li>
<li><p><code>aspatial_data_processing()</code> - this is used to process the data. The following steps are done:</p>
<ol type="1">
<li><p>Keep the necessary columns only (i.e., “KODE.KELURAHAN”, “KELURAHAN”, “SASARAN”, “BELUM.VAKSIN”). We need the “KODE.KELURAHAN” column to join the processed aspatial data with the processed geospatial data. We will look at how to do this in Section 6.1.</p></li>
<li><p>Remove the first row of the <strong>tibble data frame</strong> as it is not needed (it contains the aggregate sum of the data)</p></li>
<li><p>Check for duplicates and remove them <em>(while primary exploration of data did not show duplicates, we must still be careful as not all files have been manually checked and there is a still a chance that duplicates exist)</em></p></li>
<li><p>Check for invalid data (i.e., missing values/NA) and convert them to 0 for us to perform our calculations later on.</p></li>
<li><p>Calculate “VACCINATION.RATE”</p></li>
<li><p>Create “MONTH.YEAR” column (i.e., English translation of Month and the Year of data collected)</p></li>
</ol></li>
</ul>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Formula for Vaccination Rate is as follows:</p>
<p><span class="math inline">\(vaccination rate = (target - unvaccinated) / target\)</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>get_month_year <span class="ot">&lt;-</span> <span class="cf">function</span>(filepath) {</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># load hash library to get a hash object</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(hash)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># create hash object to map Bahasa Indonesian translation to English</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  h <span class="ot">&lt;-</span> <span class="fu">hash</span>()</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Januari"</span>]] <span class="ot">&lt;-</span> <span class="st">"January"</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Februari"</span>]] <span class="ot">&lt;-</span> <span class="st">"February"</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Maret"</span>]] <span class="ot">&lt;-</span> <span class="st">"March"</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"April"</span>]] <span class="ot">&lt;-</span> <span class="st">"April"</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Mei"</span>]] <span class="ot">&lt;-</span> <span class="st">"May"</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Juni"</span>]] <span class="ot">&lt;-</span> <span class="st">"June"</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Juli"</span>]] <span class="ot">&lt;-</span> <span class="st">"July"</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Agustus"</span>]] <span class="ot">&lt;-</span> <span class="st">"August"</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"September"</span>]] <span class="ot">&lt;-</span> <span class="st">"September"</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Oktober"</span>]] <span class="ot">&lt;-</span> <span class="st">"October"</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"November"</span>]] <span class="ot">&lt;-</span> <span class="st">"November"</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  h[[<span class="st">"Desember"</span>]] <span class="ot">&lt;-</span> <span class="st">"December"</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># get components of filepath to get date</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  components <span class="ot">=</span> <span class="fu">str_split</span>(filepath, <span class="st">" "</span>)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  month <span class="ot">=</span> h[[components[[<span class="dv">1</span>]][<span class="dv">6</span>]]]</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>  year <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">"[^0-9.-]."</span>, <span class="st">""</span>, components[[<span class="dv">1</span>]][<span class="dv">7</span>])</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (<span class="fu">paste</span>(month, year, <span class="at">sep=</span><span class="st">" "</span>))</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>hash</strong> library and method is used to create and work with has objects. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/hash/versions/3.0.1/topics/hash">here</a>.</p>
<p><code>str_split()</code> takes a character vector and returns a list. In this case, I used it to split up the <code>filepath</code> of type <em>&lt;string&gt;</em> so that I could extract the month and year. Please refer to the documentation <a href="https://stringr.tidyverse.org/reference/str_split.html">here</a>.</p>
<p><code>gsub()</code> performs replacement of the values specified in regex with the value you have specified. In this case, I simply replaced all the non-numerical values with an empty string. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/grep">here</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>aspatial_data_processing <span class="ot">&lt;-</span> <span class="cf">function</span>(filepath) {</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  vaccine_data <span class="ot">=</span> <span class="fu">read_xlsx</span>(filepath, <span class="at">.name_repair =</span> <span class="st">"universal"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># only keep the necessary columns</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  vaccine_data <span class="ot">=</span> vaccine_data[, <span class="fu">c</span>(<span class="st">"KODE.KELURAHAN"</span>, <span class="st">"KELURAHAN"</span>, <span class="st">"SASARAN"</span>, <span class="st">"BELUM.VAKSIN"</span>)]</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove the first row which has the aggregate sum of vaccination numbers</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  vaccine_data <span class="ot">=</span> vaccine_data[<span class="sc">-</span><span class="dv">1</span>, ]</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># check for duplicates and remove them</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  vaccine_data <span class="ot">&lt;-</span> vaccine_data<span class="sc">%&gt;%</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(KELURAHAN, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># check for invalid data (missing values or NA) and convert them to 0</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  vaccine_data[<span class="fu">is.na</span>(vaccine_data)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate vaccination rate - (sasaran - belum vaksin)/sasaran</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  vaccine_data<span class="sc">$</span>VACCINATION.RATE <span class="ot">=</span> (vaccine_data<span class="sc">$</span>SASARAN <span class="sc">-</span> vaccine_data<span class="sc">$</span>BELUM.VAKSIN)<span class="sc">/</span>vaccine_data<span class="sc">$</span>SASARAN</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># create date column</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>  month_year <span class="ot">&lt;-</span> <span class="fu">get_month_year</span>(filepath)</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>  vaccine_data<span class="sc">$</span>MONTH.YEAR <span class="ot">&lt;-</span> month_year</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(vaccine_data)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The argument <code>.name_repair</code> of the <code>read_xlsx()</code> method is used to automatically change column names to a certain format. “universal” names are unique and syntactic. Please refer to the documentation <a href="https://readxl.tidyverse.org/reference/read_excel.html#arguments">here</a>.</p>
<p>To remove duplicate values of a certain column, we can use the <code>distinct()</code> method. This only works for <strong>dplyr</strong> &gt;= 0.5. Please refer to this <a href="https://stackoverflow.com/questions/22959635/remove-duplicated-rows-using-dplyr">stackoverflow link</a> that explains more in-depth.</p>
<p>I have used the <code>is.na()</code> method to convert all NA values to 0. The <code>vaccine_data</code> wrapper is used to make sure we transform the data inside that variable. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/ursa/versions/3.9.4/topics/is.na">here</a>.</p>
</div>
</div>
</section>
<section id="running-aspatial_data_processing-on-aspatial-data" class="level4" data-number="5.1.3">
<h4 data-number="5.1.3" class="anchored" data-anchor-id="running-aspatial_data_processing-on-aspatial-data"><span class="header-section-number">5.1.3</span> Running <code>aspatial_data_processing()</code> on Aspatial Data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"data/aspatial"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>dflist <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_along</span>(file.list), <span class="cf">function</span>(x) <span class="fu">aspatial_data_processing</span>(file.list[x]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>seq_along()</code> is a built-in function in R that creates a vector that contains a sequence of numbers from 1 to the object’s length. You can find an in-depth explanation of this method <a href="https://r-lang.com/seq_along-function-in-r/">here</a>.</p>
<p>We used <code>seq_along()</code> to create a vector so we can use <code>lapply()</code> (which only works on lists or vectors) to apply the <code>aspatial_data_processing()</code> to all the files.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>processed_aspatial_data <span class="ot">&lt;-</span> <span class="fu">ldply</span>(dflist, data.frame)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(processed_aspatial_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,204
Columns: 6
$ KODE.KELURAHAN   &lt;chr&gt; "3172051003", "3173041007", "3175041005", "3175031003…
$ KELURAHAN        &lt;chr&gt; "ANCOL", "ANGKE", "BALE KAMBANG", "BALI MESTER", "BAM…
$ SASARAN          &lt;dbl&gt; 23947, 29381, 29074, 9752, 26285, 21566, 23886, 47898…
$ BELUM.VAKSIN     &lt;dbl&gt; 4592, 5319, 5903, 1649, 4030, 3950, 3344, 9382, 3772,…
$ VACCINATION.RATE &lt;dbl&gt; 0.8082432, 0.8189646, 0.7969664, 0.8309065, 0.8466806…
$ MONTH.YEAR       &lt;chr&gt; "February 2022", "February 2022", "February 2022", "F…</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here, we use the <code>ldply()</code> function from the <strong>plyr</strong> library to combine and return the results in a single data frame. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/plyr/versions/1.8.8/topics/ldply">here</a>.</p>
</div>
</div>
</section>
<section id="rename-columns-for-better-understanding-1" class="level4" data-number="5.1.4">
<h4 data-number="5.1.4" class="anchored" data-anchor-id="rename-columns-for-better-understanding-1"><span class="header-section-number">5.1.4</span> Rename Columns for better understanding</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>processed_aspatial_data <span class="ot">&lt;-</span> processed_aspatial_data <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">village_code =</span> KODE.KELURAHAN,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sub_district =</span> KELURAHAN,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">target =</span> SASARAN,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">not_vaccinated =</span> BELUM.VAKSIN,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">vaccination_rate =</span> VACCINATION.RATE,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_year =</span> MONTH.YEAR</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With that we have completed the Data Wrangling processes for the Aspatial Data 😎</p>
<p>Now, we can finally start analysing the data proper 📈</p>
</section>
</section>
</section>
<section id="task-1-choropleth-mapping-and-analysis" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="task-1-choropleth-mapping-and-analysis"><span class="header-section-number">6</span> Task 1: Choropleth Mapping and Analysis</h2>
<p>In Section 2 we looked at the three main objectives of this assignment. Let’s start with the first one. <em>Please take note that we have already calculated the monthly vaccination rate from July 2021 to June 2022 in section 5.1.2.</em></p>
<p>Before we can create the choropleth maps to analyse the data we will need to combine the Spatial and Aspatial data.</p>
<section id="combining-both-data-frames-using-left_join" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="combining-both-data-frames-using-left_join"><span class="header-section-number">6.1</span> Combining both data frames using <code>left_join()</code></h3>
<p>We would like to join the two data sets on the “village_code” column. Let’s take a look at the data to see if there are any discrepancies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(processed_aspatial_data<span class="sc">$</span>village_code, jakarta<span class="sc">$</span>village_code)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3101011003" "3101011002" "3101011001" "3101021003" "3101021002"
[6] "3101021001"</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>setdiff()</code> finds the (asymmetric) difference between two collections of objects. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/nat/versions/1.6.6/topics/setdiff">here</a>.</p>
</div>
</div>
<p>Hm… 🤔 while this might seem confusing at first we need to remember that we removed the outer islands from the Geospatial data in Section 4.2.4 but we didn’t do that for the Aspatial data. We don’t have to do this since <code>left_join()</code> helps us exclude these data automatically.</p>
<p>In fact, here are what these codes mean:</p>
<ul>
<li><p>“3101011003” - PULAU HARAPAN</p></li>
<li><p>“3101011002” - PULAU KELAPA</p></li>
<li><p>“3101011001” - PULAU PANGGANG</p></li>
<li><p>“3101021003” - PULAU PARI</p></li>
<li><p>“3101021002” - PULAU TIDUNG</p></li>
<li><p>“3101021001” - PULAU UNTUNG JAWA</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>jakarta_vaccination_rate <span class="ot">&lt;-</span> <span class="fu">left_join</span>(jakarta, processed_aspatial_data, <span class="at">by =</span> <span class="st">"village_code"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>left_join()</code> is a function from the <strong>dplyr</strong> library that returns all rows from X (i.e., <code>jakarta</code>) and all columns from X and Y (i.e., <code>vax_data_jakarta</code>). Please refer to the documentation <a href="https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/join">here</a>.</p>
</div>
</div>
</section>
<section id="mapping-the-distribution-of-vaccination-rate-for-dki-jakarta-over-12-months" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="mapping-the-distribution-of-vaccination-rate-for-dki-jakarta-over-12-months"><span class="header-section-number">6.2</span> Mapping the Distribution of Vaccination Rate for DKI Jakarta over 12 months</h3>
<section id="choosing-the-data-classification-method" class="level4" data-number="6.2.1">
<h4 data-number="6.2.1" class="anchored" data-anchor-id="choosing-the-data-classification-method"><span class="header-section-number">6.2.1</span> Choosing the Data Classification Method</h4>
<p>There are many data classification methods but the Natural Breaks (or “Jenks”) method is useful as the class breaks are iteratively created in a way that best groups similar values together and maximises the differences between classes. However this classification is not recommended for data with low variances (<a href="https://en.wikipedia.org/wiki/Jenks_natural_breaks_optimization#:~:text=The%20Jenks%20classification%20method%20is,values%2C%20it%20will%20identify%20them.">source</a>).</p>
<p>We can use the Coefficient of Variation (CV) to check whether or variance is large or small. As a rule of thumb a CV &gt;= 1 indicates a relatively high variation, while CV &lt; 1 can be considered low (<a href="https://statisticsbyjim.com/basics/coefficient-variation/">source</a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a helper function to calculate CV for the different month_year(s)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>print_variance <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  different_time_periods <span class="ot">=</span> <span class="fu">unique</span>(data<span class="sc">$</span>month_year)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (time_period <span class="cf">in</span> different_time_periods) {</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    temp <span class="ot">=</span> <span class="fu">filter</span>(data, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> time_period)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(time_period, <span class="st">'-'</span>, <span class="fu">sd</span>(temp<span class="sc">$</span>vaccination_rate)<span class="sc">/</span><span class="fu">mean</span>(temp<span class="sc">$</span>vaccination_rate)))</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>paste()</code> is used to concatenate vectors by converting them into characters. Here we have used it to print more than 1 variable. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/paste">here</a>.</p>
<p><code>sd()</code> computes the standard deviation of the values in <code>temp$vaccination_rate</code>. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/sd">here</a>.</p>
<p><code>mean()</code> computes the mean of the values in <code>temp$vaccination_rate</code>. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/mean">here</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call function created in the previous code chunk</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print_variance</span>(jakarta_vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "February 2022 - 0.0204124688455782"
[1] "April 2022 - 0.0195280126426937"
[1] "June 2022 - 0.019149038400642"
[1] "November 2021 - 0.0256946444161707"
[1] "September 2021 - 0.0329776110706792"
[1] "August 2021 - 0.0450062768148874"
[1] "December 2021 - 0.0225819104823015"
[1] "January 2022 - 0.0207887827395515"
[1] "July 2021 - 0.0981352771312773"
[1] "March 2022 - 0.0198328772481761"
[1] "May 2022 - 0.0194085783913278"
[1] "October 2021 - 0.0289456339694201"</code></pre>
</div>
</div>
<p>From the above output, we can see that the CV for the vaccination_rate is pretty low. So maybe “Jenks” isn’t the best method.</p>
<p>Another data classification method is the “Equal Interval” method. As Professor Kam has mentioned in his <a href="https://is415-ay2022-23t2.netlify.app/lesson/lesson03/lesson03-thematic_and_analytical_mapping#/9">slides</a>, this method divides the <code>vaccination_rate</code> values into equally sized classes. However, we should avoid this method if the data is skewed to one end or if we have 1 or 2 really large outlier values.</p>
<p>So let’s check our data if it is skewed and if it has any outliers. For this, we will be using the <code>skewness()</code> and <code>hist()</code> methods to calculate the skewness and visualise the data respectively. Do note that as a rule of thumb if the skewness value is between -0.5 and 0.5 the data is relatively symmetrical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a helper function to calculate skewness for the different month_year(s)</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>print_skewness <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  different_time_periods <span class="ot">=</span> <span class="fu">unique</span>(data<span class="sc">$</span>month_year)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (time_period <span class="cf">in</span> different_time_periods) {</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    temp <span class="ot">=</span> <span class="fu">filter</span>(data, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> time_period)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(time_period, <span class="st">'-'</span>, moments<span class="sc">::</span><span class="fu">skewness</span>(temp<span class="sc">$</span>vaccination_rate)))</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>skewness()</code> computes the skewness of the data given (i.e., <code>temp$vaccination_rate</code>). Please refer to the documentation <a href="https://www.rdocumentation.org/packages/e1071/versions/1.7-13/topics/skewness">here</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call function created in the previous code chunk</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print_skewness</span>(jakarta_vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "February 2022 - -0.295699763720069"
[1] "April 2022 - -0.265297167937898"
[1] "June 2022 - -0.270797534250581"
[1] "November 2021 - -0.486301892731201"
[1] "September 2021 - -0.139155729188301"
[1] "August 2021 - 0.0964932215434923"
[1] "December 2021 - -0.392411450973568"
[1] "January 2022 - -0.349709242169843"
[1] "July 2021 - -0.0428275905167636"
[1] "March 2022 - -0.256095796585012"
[1] "May 2022 - -0.266302251476784"
[1] "October 2021 - -0.378649334850257"</code></pre>
</div>
</div>
<p>From the above output we can see that all the data is relatively symmetrical. 😌</p>
<p>Let’s plot the histograms to check if outliers are present as well!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a helper function to draw histogram for the different month_year(s)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>hist_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(df, time_period) {</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">filter</span>(jakarta_vaccination_rate, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> time_period)<span class="sc">$</span>vaccination_rate, <span class="at">ylab=</span><span class="cn">NULL</span>, <span class="at">main=</span>time_period, <span class="at">xlab=</span><span class="cn">NULL</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>hist()</code> computes a histogram of the given values. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist">here</a>.</p>
<p>We used this method as it is the easiest way to detect outliers (<a href="https://www.reneshbedre.com/blog/find-outliers.html#histogram-scatterplot-and-boxplot">source</a>). Especially if the dataset is quite small.</p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call function created in the previous code chunk</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"July 2021"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"August 2021"</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"September 2021"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"October 2021"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"November 2021"</span>)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"December 2021"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call function created in the previous code chunk</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"January 2022"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"February 2022"</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"March 2022"</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"April 2022"</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"May 2022"</span>)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(jakarta_vaccination_rate, <span class="st">"June 2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From our findings, we can say that the data is not skewed and there are not major outliers that we need to worry about 🥳 Hence, the “Equal Interval” method will be perfect for our choropleth maps.</p>
</section>
<section id="spatio-temporal-mapping-with-custom-breakpoints" class="level4" data-number="6.2.2">
<h4 data-number="6.2.2" class="anchored" data-anchor-id="spatio-temporal-mapping-with-custom-breakpoints"><span class="header-section-number">6.2.2</span> Spatio-Temporal Mapping with custom breakpoints</h4>
<p>To analyse the spatio-temporal change in vaccination rates over time we should use the same data classification method and use the same class intervals. This makes it easier for any comparisons to be made.</p>
<ul>
<li><p>The Equal Interval data classification method will be utilised (as discussed in Section 6.2.1).</p></li>
<li><p>We will need to define our custom breaks to have a common classification scheme for the COVID-19 vaccination rates.</p></li>
</ul>
<p>Let’s take a look at the summary statistics for vaccination rates across the 12 months to determine the breakpoints:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary stats for Vaccination Rates in July 2021</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">filter</span>(jakarta_vaccination_rate, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"July 2021"</span>)<span class="sc">$</span>vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3701  0.4759  0.5134  0.5107  0.5419  0.6520 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary stats for Vaccination Rates in November 2021</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">filter</span>(jakarta_vaccination_rate, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"November 2021"</span>)<span class="sc">$</span>vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7385  0.7980  0.8114  0.8094  0.8232  0.8750 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary stats for Vaccination Rates in March 2022</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">filter</span>(jakarta_vaccination_rate, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"March 2022"</span>)<span class="sc">$</span>vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7766  0.8260  0.8354  0.8353  0.8453  0.8946 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary stats for Vaccination Rates in June 2022</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">filter</span>(jakarta_vaccination_rate, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"June 2022"</span>)<span class="sc">$</span>vaccination_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7831  0.8318  0.8403  0.8408  0.8505  0.8978 </code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>summary()</code> is a generic function used to produce result summaries as shown above. Please refer to the documentation <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary">here</a>. We used this here to find out the range of vaccination rates over the 12 months. We can see that the range is from 0.3701 to 0.8978.</p>
</div>
</div>
<p>Hence, breakpoints can be defined with intervals of 0.1 where values range from 0.3 to 0.9.</p>
<p>Since we need to plot a map for each month let’s start by creating a generic helper function to do it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a helper function to plot the choropleth map</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>choropleth_plotting <span class="ot">&lt;-</span> <span class="cf">function</span>(df, month_name) {</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  temp <span class="ot">=</span> <span class="fu">filter</span>(df, <span class="st">`</span><span class="at">month_year</span><span class="st">`</span> <span class="sc">==</span> month_name)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(temp)<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"vaccination_rate"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.5</span>, <span class="fl">0.6</span>, <span class="fl">0.7</span>, <span class="fl">0.8</span>, <span class="fl">0.9</span>),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Vaccination Rate"</span>,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">legend.hist =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> month_name,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.40</span>, </span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.25</span>,</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span><span class="fl">0.2</span>)</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call the functions for all the different months</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"July 2021"</span>),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"August 2021"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call the functions for all the different months</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"September 2021"</span>),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"October 2021"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"November 2021"</span>),</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"December 2021"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"January 2022"</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"February 2022"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"March 2022"</span>),</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"April 2022"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"May 2022"</span>),</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">choropleth_plotting</span>(jakarta_vaccination_rate, <span class="st">"June 2022"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="take-home_ex02_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="observations-from-equal-interval-choropleth-maps-with-custom-breakpoints" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="observations-from-equal-interval-choropleth-maps-with-custom-breakpoints"><span class="header-section-number">6.3</span> Observations from Equal Interval Choropleth Maps with Custom Breakpoints</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ezgif.com-optimize.gif" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption"><em>The above gif was made by stitching the individual choropleths we created earlier on <a href="https://ezgif.com/maker">ezgif</a>.</em></figcaption><p></p>
</figure>
</div>
<ul>
<li><p>There was an increase in vaccination rate all over Jakarta. There doesn’t seem to be a single point from which it starts. However, it should be noted that top 3 sub-districts with the highest vaccination rates in July 2021 were <strong>Kamal Muara</strong>, <strong>Halim Perdana Kusuma</strong>, and <strong>Kelapa Gading Timur</strong>. While Halim Perdana Kusuma was still in the top 3 after a year, Kamal Muara and Kelapa Gading Timur were replaced by <strong>Srengseng Sawah</strong> and <strong>Mabggarai Selatan</strong>. Halim Perdana Kusuma remained one of the highest as it had a relatively low target of 28363.</p></li>
<li><p>After a year, the lowest vaccination rate in a sub-district was 78%. With this, we can see that the generally the population of Jakarta was very receptive to the COVID-19 vaccines.</p></li>
<li><p>Additionally, the gif tells us that the receptiveness of the vaccine seem to spread “inwards” where the bigger sub-districts tend to reach a higher vaccination rate quicker and gaps between them (i.e., the smaller sub-districts) were “filled-in” later on. Therefore, unequal distribution of vaccination rates among the sub-districts could possibly be attributed to their size. The Indonesian government might have focused their efforts on the largely populated areas to attain herd immunity quicker.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>